# Generated by Django 2.1.5 on 2019-01-27 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abiturient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, verbose_name='ФИО')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlisted', models.BooleanField(default=False)),
                ('abiturient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='write_db.Abiturient')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, verbose_name='Город(местой проживание)')),
            ],
        ),
        migrations.CreateModel(
            name='Countr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Facully',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150, verbose_name='Спецальность')),
                ('fac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='write_db.Facully')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='special',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='write_db.Special'),
        ),
        migrations.AddField(
            model_name='abiturient',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='write_db.Area'),
        ),
        migrations.AddField(
            model_name='abiturient',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='write_db.City'),
        ),
        migrations.AddField(
            model_name='abiturient',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='write_db.Countr'),
        ),
        migrations.AddField(
            model_name='abiturient',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='write_db.Region'),
        ),
    ]
