# Generated by Django 2.1.5 on 2019-01-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('write_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAbiturient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'blog_abiturient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlisted', models.BooleanField()),
            ],
            options={
                'db_table': 'blog_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'blog_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'blog_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogCountr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'blog_countr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogFacully',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'blog_facully',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'blog_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlogSpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'blog_special',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='abiturient',
            name='area',
        ),
        migrations.RemoveField(
            model_name='abiturient',
            name='city',
        ),
        migrations.RemoveField(
            model_name='abiturient',
            name='country',
        ),
        migrations.RemoveField(
            model_name='abiturient',
            name='region',
        ),
        migrations.RemoveField(
            model_name='application',
            name='abiturient',
        ),
        migrations.RemoveField(
            model_name='application',
            name='special',
        ),
        migrations.RemoveField(
            model_name='special',
            name='fac',
        ),
        migrations.DeleteModel(
            name='Abiturient',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Countr',
        ),
        migrations.DeleteModel(
            name='Facully',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Special',
        ),
    ]
